Repository sef-global/sef-site, pull requests merged in 2022-10, with the labels that each got.

#1218 Create SEF dummy dev page
  assets/content/static/navbar.html
  assets/img/deve-page-hero.png
  assets/img/projects/elixir.png
  devpage.html
Labels: hacktoberfest-accepted

#1226 Add Success Stories page with dynamic content
  success_stories/functions.js
  success_stories/index.html
  success_stories/styles.css
Labels: hacktoberfest-accepted

#1232 Update index.html
  scholarx/2022/index.html
Labels: hacktoberfest-accepted

#1240 Fix Overlapping in Testimonial Section in Mobile View
  assets/css/global-custom.css
Labels: hacktoberfest-accepted

#1249 Add a loading skeleton to success stories page
  success_stories/index.html
  success_stories/styles.css
Labels: hacktoberfest-accepted

#1242 Added spacing between buttons in mobile view in Dev Page
  devpage.html
Labels: hacktoberfest-accepted

#1251 Update the Slack invitation link
  assets/content/static/footer.html
  assets/content/static/navbar.html
Labels: hacktoberfest-accepted

#1252 Make homepage elements center aligned on mobile devices
  index.html
Labels: hacktoberfest-accepted

#1260 Reduce font size of success story card titles on mobile view
  success_stories/styles.css
Labels: hacktoberfest-accepted

#1263 Changed the required directory to success-stories
  success-stories/functions.js
  success-stories/index.html
  success-stories/styles.css
Labels: hacktoberfest-accepted

#1264 Added the meta tag in the Engineering Team page
  devpage.html
Labels: hacktoberfest-accepted

#1259 Add a section to the ScholarX page to access the success stories page
  scholarx/2022/images/success.png
  scholarx/2022/index.html
Labels: hacktoberfest-accepted

#1270 Increase the margin of the Apply Now button in Join Us Page
  join-us.html
Labels: hacktoberfest-accepted

#1268 Fix the Success Stories page footer thematic break is went down
  success-stories/styles.css
Labels: hacktoberfest-accepted

#1273 Fix the slack and hive link in the nav bar to open in a new window
  assets/content/static/navbar.html
Labels: hacktoberfest-accepted

#1277 Fix ScholarX 2022 page alignment
  scholarx/2022/index.html
Labels: hacktoberfest-accepted

#1280 Fix thematic break styles
  success-stories/styles.css
Labels: hacktoberfest-accepted

#1269 Add margin for icon
  assets/content/static/footer.html
Labels: hacktoberfest-accepted

#1292 Move scholarx success stories folder inside the scholax folder
  scholarx/2022/index.html
  scholarx/success-stories/functions.js
  scholarx/success-stories/index.html
  scholarx/success-stories/styles.css
Labels: hacktoberfest-accepted

#1304 Fix the colliding of two buttons
  devpage.html
Labels: hacktoberfest

#1278 Fix the Scholarx page alignments
  scholarx/2022/index.html
Labels: hacktoberfest-accepted

#1319 Fix text align issues in the home page
  index.html
Labels: hacktoberfest-accepted

#1325 Reduce the gap between the button and the topic in the IRC Page
  irc.html
Labels: hacktoberfest-accepted

#1329 Add leaderboard link to nav bar
  assets/content/static/navbar.html
Labels: hacktoberfest-accepted

#1333 Remove script folder
  scripts/surge_deploy.sh
Labels: hacktoberfest-accepted

#1337 Fix the alignment of the up speak page's tablet view
  upspeak/index.html
Labels: hacktoberfest-accepted

#1350 Remove white outlines from buttons
  onelive/archive/index.html
  onelive/index.html
Labels: hacktoberfest-accepted

#1351 Fix the alignments in the all Pages breaking from the navbar
  assets/content/static/navbar.html
Labels: hacktoberfest

#1353 Align the icons center in the First Section in the home page
  index.html
Labels: hacktoberfest-accepted

#1347 Restructure the code of footer
  assets/content/static/footer.html
Labels: hacktoberfest-accepted

#1315 Re adjust the readme logo and link
  assets/img/logos/ReadMe-Coloured-728x160.png
  index.html
Labels: hacktoberfest-accepted

#1244 Rename devpage.html file
  assets/content/static/navbar.html
  engineering-team.html
Labels: hacktoberfest-accepted

#1360 Decrease the margin between the navbar and the home page header section
  index.html
Labels: hacktoberfest-accepted

#1359 Add project cards to engineering team page
  engineering-team.html
Labels: hacktoberfest-accepted

#1379 Update the PR template
  .github/pull_request_template.md
Labels: hacktoberfest-accepted, pending-review
